# Requirements of this Ansible project
#
# This file defines required roles and/or collections of this Ansible
# project that can be installed using the following command:
#
#     ansible-galaxy install -r requirements.yml
#
# References:
#
# * Installing multiple roles from a file — Galaxy User Guide — Ansible
#   Community Documentation
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file
# * Installing roles and collections from the same requirements.yml file
#   — Galaxy User Guide — Ansible Community Documentation
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0 OR LicenseRef-Apache-2.0-If-Not-Used-In-Template-Projects
---
roles: []
  # Install a role from Ansible Galaxy.
  #- name: geerlingguy.java
  #  version: "1.9.6"

collections:
  # Dependency of the community.general.yaml callback plugin
  - name: community.general
    version: ">=9.0.0"
