# The main handler definition file of the Ansible role
#
# Copyright 2024 The common Ansible role template contributors <https://github.com/the-common/ansible-role-template/graphs/contributors>
# SPDX-License-Identifier: CC-BY-SA-4.0+ OR LicenseRef-Apache-2.0-If-Not-Used-In-Template-Projects

#- name: Define a task to do something using the _module_ module when notified by another task via the `notify` task property.
#  _module_:
#    _module_args_
